# Generated by Django 4.1.3 on 2022-11-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_follow_follow_unique_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
